version: "3.5"
services:
    arangodb:
      container_name: arangodb
      image: arangodb/arangodb:3.9.1
      ports:
        - 8529:8529
      expose:
        - 8529
      volumes:
        - ./store/arangodb3:/var/lib/arangodb3:rw
        - ./store/arangodb3-apps:/var/lib/arangodb3-apps:rw
      environment:
         - ARANGO_ROOT_PASSWORD=root

    init:
      container_name: arangoinit
      image: ralphschaefer/arangodb-cloudinit:0.4.0
      volumes:
        - ./config:/config
      environment:
        - ARANGODB_ROOTUSER=root
        - ARANGODB_ROOTPASS=root
        - ARANGODB_ENDPOINT=http://arangodb:8529
        - ARANGODB_TIMEOUT=5s
        - ARANGODB_RETRY=20
      depends_on:
        - "arangodb"


