databases:
  - name: "aaaa"
    owner:
      name: "hhhh"
      password: "pass"
    collections:
      - name: "users"
        compositeindex:
          - fields: ["email", "name"]
            options: ["unique"]
        index:
          - field: "name"
            options: ["sparse"]
        documents:
          - key: "root"
            value: '{"name": "admin", "email": "admin@admin", "humanReadableName": "Dr. Hans Wurst"}'
          - key: "test"
            value: '{"name": "test", "email": "test@user", "humanReadableName": "Max Mustermann"}'
          - key: "test2"
            value: '{"name": "test", "email": "test2@user", "humanReadableName": "Max Mustermann"}'
      - name: "dddddd"
        index: []
        compositeindex: []
  - name: "bbbb"
    owner:
      name: "sdsdf"
      password: "sdfgsdfgd"
    collections:
      - name: "asasa"
        index: ["ddd", "ffff"]
      - name: "dddddd"
        index: ["ddd", "ffff"]