databases:
  - name: "aaaa"
    owner:
      name: "hhhh"
      password: "pass"
    collections:
      - name: "users"
        index: ["name"]
        documents:
          - key: "root"
            value: '{"name": "admin", "email": "admin@admin", "humanReadableName": "Dr. Hans Wurst"}'
          - key: "test"
            value: '{"name": "test", "email": "test@user", "humanReadableName": "Max Mustermann"}'
      - name: "dddddd"
        index: []
  - name: "bbbb"
    owner:
      name: "sdsdf"
      password: "sdfgsdfgd"
    collections:
      - name: "asasa"
        index: ["ddd", "ffff"]
      - name: "dddddd"
        index: ["ddd", "ffff"]